### ISSUE TITLE
Monitor offline reports

### ISSUE THREAD

**Issue by lsaether** [w3f/1k-validators-be#115]
and alert the Riot room when a validator was reported offline. Decide on the tolerance of offline reports before docking the rank of the validator.

**Comment by lsaether** [comment]
Offline report here could mean the on-chain "offline" or just when the node disconnects from Telemetry.

**Comment by wpank** [comment]
I would assume faults most of the time are the result of being offline. As such can send a riot message to the channel whenever that happens tagging the person
