### ISSUE TITLE
Consider switching `request` with `axios`

### ISSUE THREAD

**Issue by Nexus2k** [w3f/1k-validators-be#1365]
request module seems to be deprecated: https://github.com/request/request/issues/3143 most popular replacement choice seems axios.

**Comment by wpank** [comment]
I think this does use Axios already. Is there somewhere using request?

**Comment by Nexus2k** [comment]
iiuc package.json still references requests. no?

**Comment by Nexus2k** [comment]
https://github.com/w3f/1k-validators-be/blob/master/yarn.lock#L2963 ah dependency from matrix-js-sdk, maybe there's an newer version?
