### ISSUE TITLE
Major Update Detected for bitnami/mongodb to 3.0.5-1

### ISSUE THREAD

**Issue by mohamedhabas11** [w3f/1k-validators-be#1528]
Please investigate Major Update:

Local References are:

- https://github.com/w3f/1k-validators-be/blob/master/helmfile.d/config/kusama/mongodb.yaml.gotmpl
- https://github.com/w3f/1k-validators-be/blob/master/helmfile.d/config/polkadot/mongodb.yaml.gotmpl

**Comment by wpank** [comment]
```
image:
  registry: docker.io
  repository: bitnami/mongodb
  tag: 4.4.10-debian-10-r44
  pullPolicy: IfNotPresent
  debug: false
```

I think this is on `4.4.10` - is there a newer version? Confused by the `3.0.5-1` in the title

**Comment by Nexus2k** [comment]
iiuc 3.0.5-1 is the Helmchart version. While 4.4.10 is the docker image version

**Comment by mohamedhabas11** [comment]
@wpank sorry for the confusion.

indeed i was referring to the Helmchart version, as @Nexus2k mentioned.

image tags are now inherited from the chart, so we are good here.
