### ISSUE TITLE
Consider adding a grace window for the latest referendum

### ISSUE THREAD

**Issue by kureus** [w3f/1k-validators-be#1734]
As of v2.6.0, the current implementation means that as soon as a new referendum is released and picked up by the 1KV monitor any validator that has not voted is implicitly considered to have missed the latest vote. This means they lose 15 points awarded for voting on the latest referendum, and their consistency multipliers are trashed.

A concrete example. On Saturday April 2nd referendum 184 was released on Kusama. Taking one of the validators we operate, fireproof, `J3f7ULfjVbbBYvZtMvaEDiUC8odXjt2A2hGShshBFCKHazY`, it's democracy score was 120 before the referendum was released, 81 after it was released, and 126 after it placed its vote.

Given referendum's last 7 days, validators should be given a 24 hour grace window from the referendum appearing before it 'becomes' the latest referendum. This would still reward prompt voting but wouldn't crush scores of those who couldn't or didn't react immediately in the meantime.

**Comment by wpank** [comment]
Closing this as gov scoring is being removed
