### ISSUE TITLE
Proposal: increase self-bond scoring weight to 200 points

### ISSUE THREAD

**Issue by ArthurHoeke** [w3f/1k-validators-be#1851]
As discussed in the 1kv Polkadot element room, I'd like to request the self-bond scoring weight to be increased to 200 points.

Currently there is virtually no benefit to having a high self-bond, validators which have joined the programme on good intention get the same amount of elections as those with over 10,000 $DOT bonded. Encouraging validators to have a high self-bond is important to push operators towards becoming a trustworthy and independant brand.

If the self-bond weight won't be changed sufficiently, 1kv validators will likely unbond funds to be used for staking and recouping maintenance costs. By not staking funds validators currently miss out on ~3.86 DOT ($28.74) every single day (when bonding 10,000 $DOT).

Those with high self-bond show confidence in their validator operation and endure additional expense. These validators should be rewarded accordingly.

**Comment by Nexus2k** [comment]
I personally belive that having contributed to the community and having passed the good intentions evaluation is more valuable than being able to show strong financial support for the validator.

Maybe it would be worthwhile if we can explore the option of rewarding people with high self-stake and great community contributions to get the good intention status, so they can release their self-stake.

**Comment by ArthurHoeke** [comment]
> I personally belive that having contributed to the community and having passed the good intentions evaluation is more valuable than being able to show strong financial support for the validator.
> 
> Maybe it would be worthwhile if we can explore the option of rewarding people with high self-stake and great community contributions to get the good intention status, so they can release their self-stake.

I strongly disagree, at the end of the day the goal for 1kv is to create validators which are self-sustained and get into the election cycle by themselves. Having a substantial amount of skin in the game ensures proper validator management, which is good for the network and stakers. Further more it encourages decentralisation. You won't want to host on AWS for example in case of a black swan event and possibly get slashed losing your self-bond.

Community contributions are great, though you cannot run a network on it.

**Comment by Noc2** [comment]
Thanks for bringing this up: Maybe it’s best to discuss this here: https://gist.github.com/wpank/054ba0170e21786e4e8acaed9dbea7c1 together with all other ideas/changes.
