### ISSUE TITLE
Duplicate stash in polkadot api

### ISSUE THREAD

**Issue by dcolley** [w3f/1k-validators-be#1874]
https://polkadot.w3f.community/candidates contains 2 entries for :
1NDRMvN7FH9YtJLVPf9doF5zbuUwn6hdH1b4WmVyZDr5joM

<img width="826" alt="image" src="https://user-images.githubusercontent.com/1845970/177690741-de9fc548-e247-4243-b779-45ba550794c6.png">

Is this intentional?

**Comment by Nexus2k** [comment]
@wpank for some visibility

**Comment by wpank** [comment]
merged the entries
