### ISSUE TITLE
inclusion rate is not updated for many nodes

### ISSUE THREAD

**Issue by MathCryptoDoc** [w3f/1k-validators-be#1973]
The inclusion rate in the json is not updated reliably since Sept 10. Many nodes that are not active / nominated have a constant inclusion rate. This has a big negative impact on the calculated inclusion scores (200 in total) keeping these nodes from being selected.

Here is a graph of my two nodes. These are not an exception.

![inclusion](https://user-images.githubusercontent.com/104353188/190073953-473aeaa2-ae48-45ff-af4a-f7382ffc437c.png)

However, not all nodes have constant score. If they are active, the score changes.

**Comment by MathCryptoDoc** [comment]
Small update: over the last 24h, the inclusion field got updated once. However, before it updated more than once a day. Maybe every hour?

![inclusion](https://user-images.githubusercontent.com/104353188/190143720-62b2d616-5065-4925-9ec8-9ed08c5932ed.png)

**Comment by MathCryptoDoc** [comment]
The backend is updating the inclusion rate regularly again. Here is an example of the 2 nodes and 4 additional ones (no legend for privacy reasons).

![inclusion](https://user-images.githubusercontent.com/104353188/190960455-f40cb517-8507-496c-bc32-7ab871ef5dc3.png)

Feel free to close this issue since it seems to fixed (for now?).

**Comment by MathCryptoDoc** [comment]
Spoke too soon. The inclusion rate stays again constant for nodes that have not been active. The rate should decrease with each hour. In addition, the ``score.updated`` field is not even updated for many nodes.

![inclusion](https://user-images.githubusercontent.com/104353188/192107504-7fc1fef9-5ef0-4e87-ad47-21a144de25d3.png)

**Comment by wpank** [comment]
closing this as it's likely outdated
