### ISSUE TITLE
"Internet service providers" are scored the same as "hosting providers"

### ISSUE THREAD

**Issue by aperture-sandi** [w3f/1k-validators-be#2416]
It seems that the current system treats "Internet service providers" the same as "hosting providers".  But I assume that is not the intention.  For example 10 nodes in ten different cities could all be "self-hosting" using "Verizon Business" as an ISP and be penalized for using the same "provider".  Perhaps the location name should be tacked onto the end of ISP names.  For example "Verizon Business-New York City" or "Verizon Business-Scranton".

**Comment by leeclemens** [comment]
I personally think it makes sense to differentiate. Also, any "hosting provider" will hopefully be using multiple ISPs.

But given this example, what if "Verizon Business" decides to ban any crypto-related traffic? Just one hypothetical example of how ISP diversification can be crucial.

**Comment by aperture-sandi** [comment]
If Verizon decides to ban crypto traffic, that will likely take out half of the hosting providers in North America.  
If hosting provider's Internet service providers aren't scored, then Internet service providers shouldn't be scored as a whole for "self-hosting" nodes.  

Other thoughts: Even if a self-hosted validator got Dedicated Internet Access in an area with "Verizon Business" the DIA could still be though Verizon.  So the "organization" attached to node's IP would change but the underling ISP would still be Verizon.

**Comment by leeclemens** [comment]
> If Verizon decides to ban crypto traffic, that will likely take out half of the nodes at hosting providers in North America.

I think that's a good reason to not consider many locations as different when they share the underlying company. I believe your proposal would remove that distinction and treat the "Verizon Business" nodes as diverse, when they share a common single point of failure.

> If hosting provider's Internet service providers aren't scored, then Internet service providers shouldn't be scored as a whole for "self-hosting" nodes.

It seems more difficult to track, but if a hosting provider has redundant ISPs - any single ISP seems less relevant to overall availability. If you only have one ISP, that particular ISP is far more significant in terms of availability.

> Other thoughts: Even if a self-hosted validator got Dedicated Internet Access in an area with "Verizon Business" the DIA could still be though Verizon. So the "organization" attached to node's IP would change but the underling ISP would still be Verizon.

I think you can still determine this, but I'm not sure how robust the application is that checks it.

**Comment by aperture-sandi** [comment]
The point I'm trying to make is the current "provider" scoring system does not take ISP into account. The purpose of this issue is to simply align "ISP names" with the current "provider" scoring system logic.  

If you are suggesting ISP should be taken into account in scoring that probably is a separate issue.

**Comment by leeclemens** [comment]
I believe your suggestion will make validator nodes falsely appear more diverse/reliable/etc while sharing single points of failure/vulnerabilities. I'm simply responding to your idea and sharing my concerns.

**Comment by wpank** [comment]
Closing this as it's likely outdated, if it's still an issue feel free to reopen
