### ISSUE TITLE
Missing Polkadot Gov v1 Votes

### ISSUE THREAD

**Issue by aperture-sandi** [w3f/1k-validators-be#2422]
It appears that the backend is not picking up all gov v1 votes.  For example...

DOT stash 145SvVXoAwR5ufJynYWDeNXzfyxbf5VkCqkHu3Jt7FSdYBE2 voted for referenda 120 and 121 but this information is missing from the 1KV scoring database.

See chain data here:
https://polkadot.subscan.io/extrinsic/15635706-2
https://polkadot.subscan.io/extrinsic/15635701-2

![image](https://github.com/w3f/1k-validators-be/assets/88592169/86d6a05e-bae5-4ef6-ada8-73061a0f148c)

Chain state...
 ```
    [
        120
        {
          Standard: {
            vote: {
              conviction: Locked1x
              vote: Aye
            }
            balance: 5,011,000,000,000
          }
        }
      ]
      [
        121
        {
          Standard: {
            vote: {
              conviction: Locked1x
              vote: Aye
            }
            balance: 5,011,000,000,000
          }
        }
      ]
```

**Comment by lesnikutsa** [comment]
We also faced the same problem on our account 15wnPRex2QwgWNCMRVSqgqp2syDn8Gf6LPGGabRhA8zoohpt. For the validator, we use LEDGER together with a PROXY account. We voted for all possible GOVs first through PROXY, but only 1 vote (123 was credited to the 1KV), although all transactions were successful. Yesterday we re-voted with LEDGER as our democracy, referenda and council votes still don't count.
