### ISSUE TITLE
Provider points calculation appears to be bugged 

### ISSUE THREAD

**Issue by aperture-sandi** [w3f/1k-validators-be#2463]
We have observed "provider" points for stash 145SvVXoAwR5ufJynYWDeNXzfyxbf5VkCqkHu3Jt7FSdYBE2 bouncing between 50 and 100 points despite being the only Validator using provider "Verizon Business". See an image of the backend data below showing a provider score of 50... (I did a search of the data as you can see the search returned 1 of 1)

![image](https://github.com/w3f/1k-validators-be/assets/88592169/55d90162-4e83-492d-91ac-ca5483d2c221)

In addition see attached graph of provider score generated by math-crypto for stash 145SvVXoAwR5ufJynYWDeNXzfyxbf5VkCqkHu3Jt7FSdYBE2 below

![image](https://github.com/w3f/1k-validators-be/assets/88592169/b42f9b29-c92d-43e0-be98-d77adc682d18)

Link to live data: https://insights.math-crypto.com/polkadot/145SvVXoAwR5ufJynYWDeNXzfyxbf5VkCqkHu3Jt7FSdYBE2/

**Comment by wpank** [comment]
Closing this as it's likely outdated, if it's still an issue feel free to reopen
