### ISSUE TITLE
Documentation & Setup Configurations

### ISSUE THREAD

**Issue by wpank** [w3f/1k-validators-be#2488]
- [x] Root level README
- [x] Revise Core README
- [ ] Gateway README
- [ ] Worker README
- [ ] Telemetry README
- [x] Current Architecture Diagram
- [x] Microservice Diagram
- [x] Running local dev docker-compose
- [x] Running prod microservice docker-compose
- [x] Running prod current docker-compose
- [x] Docusaurus
- [x] Creating config files

**Comment by ironoa** [comment]
Naming Convention:
- current version == monolithic version
- next version == microservices version

**Comment by ironoa** [comment]
- [ ] current docker-compose should reflect exactly the deployed version in production

**Comment by wpank** [comment]
> * [ ]  current docker-compose should reflect exactly the deployed version in production

To have the different versions I would suggest having there be 3 docker-compose files:
- `docker-compose.yml` (this is the dev local one - with everything. It uses the `Dockerfile-dev`images that are in each package as is)
- `docker-compose.current.yml` (this uses the regular `Dockerfile` in just the core, and reflects the what is currently deployed)
- `docker-compose.microservice.yml` (uses regular `Dockerfile`in each package, runs additionally redis, gateway, worker, etc)

However those docker-compose files are names feel free to suggest other names, but in general would have 3 docker-compose files with the above things in them.

**Comment by wpank** [comment]
Root Package Config Generation:
- [ ] Current Kusama (generates the config as is in production for the Kusama instance)
- [ ] Current Polkadot (generates teh config as is in production for the Polkadot instance)
- [ ] Microservice Kusama (generates the config as microservices for Kusama with production values)
- [ ] Microservice Polkadot (generates teh config as microservices for Polkadot with production values)
- [ ] Current Kusama Dev (generates the config reflecting the current deployed Kusama instance but with shorter cron times)
- [ ] Current Polkadot (generates the config reflecting the current deployed Polkadot instance but with shorter cron times)
- [ ] Microservice Kusama (generates the config as microservices for Kusama with shorter cron times)
- [ ] Microservice Polkadot (generates teh config as microservices for Polkadot  with shorter cron times)

**Comment by ironoa** [comment]
> * [ ]  current docker-compose should reflect exactly the deployed version in production

Hey @wpank, after running

```
yarn create-current-kusama-config
docker-compose -f docker-compose.current.yml up -d --build
```

I get 

<img width="432" alt="image" src="https://github.com/w3f/1k-validators-be/assets/25957738/1517593c-269f-485b-90aa-218978516aa1">

but with `docker compose -a` we can see that the backend instance has an issue:

<img width="1151" alt="image" src="https://github.com/w3f/1k-validators-be/assets/25957738/f86f5f50-5b71-4f80-9efa-3d7eda8ce5ad">

<img width="1151" alt="image" src="https://github.com/w3f/1k-validators-be/assets/25957738/02b89194-4b36-4c87-9223-53ce298e64ea">

**Comment by ironoa** [comment]
- [ ] I also suggest to bind the ports to localhost, you probably don't want to expose them to the internet while you are testing (i.e. [here](https://github.com/w3f/1k-validators-be/blob/master/docker-compose.current.yml#L21) should be '127.0.0.1:27017:27017')

**Comment by ironoa** [comment]
- [ ] `docker-compose` is [deprecated](https://docs.docker.com/compose/migrate/), use `docker compose`
- [ ] documentation of config values (i.e. constraints, cron, global.bootstrap/test/retroactive, ...)
- [ ] I would remove the installation commands for docker from the main readme, you could link an external resource, i.e. [this one](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-22-04) is usually pretty valid. Wdyt ?

**Comment by ironoa** [comment]
related to the `microservice` version: 

- [ ] gateway has a configuration issue: it seems to need the global section such as the core... the [sample config](https://github.com/w3f/1k-validators-be/blob/master/packages/gateway/config/sample.json) file is not reflecting that
![image](https://github.com/w3f/1k-validators-be/assets/25957738/93e6f812-e9b5-4692-9d31-40969d4b1716)
- [ ] telemetry microservice needs a healthcheck endpoint
- [ ] gateway microservice needs a healthcheck endpoint
- [ ] core microservice needs a healthcheck endpoint

**Comment by ironoa** [comment]
- [ ] prepare the deployment of production (announcement)

**Comment by ironoa** [comment]
https://github.com/w3f/1k-validators-be/pull/2503
