### ISSUE TITLE
My validator is duplicated here https://polkadot.w3f.community/candidates.

### ISSUE THREAD

**Issue by rhombusvalidator** [w3f/1k-validators-be#2496]
Hi, I'm having a problem with the scoring. As I noticed my validator is duplicated here https://polkadot.w3f.community/candidates. Because of this, it is not calculating points correctly, and those categories for which I should get 100, I get 50 and so on. Please sort out this situation.
13r8ZXgYi7KZPhAVXjpznzbmyXwWBegebtr5gJwUnvNYXwp
![1](https://github.com/w3f/1k-validators-be/assets/152792757/64cdf3b0-19e4-404c-8619-5968d0757875)

![2](https://github.com/w3f/1k-validators-be/assets/152792757/943bc502-6261-49d1-abbe-d88632948467)

**Comment by wpank** [comment]
Sorry, looks like there was two entries in the db. Should be fixed now
