### ISSUE TITLE
Nominated score

### ISSUE THREAD

**Issue by ironoa** [w3f/1k-validators-be#2502]
In my opinion, the Nominated score should take into account whether the nomination a validator received from the 1kv successfully landed him in the active set.

There are situations where a validator receives a nomination (with sufficient stake in place) but is not subsequently selected by Phragmen (due to bad luck).

A potential solution could involve introducing a metric such as NominatedAndActive, where the score does not reset to zero if the received nomination does not result in the validator being included in the active set.

**Comment by ironoa** [comment]
may be related:
![image](https://github.com/w3f/1k-validators-be/assets/25957738/5ab33e72-9453-4c1c-b654-2365d0d94522)

**Comment by ironoa** [comment]
Possible quick solution: **nomination score should take in consideration the last time someone was in the active set**. Period. This may put someone that gets nominated not by the 1kv in disadvantage, but it is a tradeoff for now.

**Comment by ironoa** [comment]
> Possible quick solution: **nomination score should take in consideration the last time someone was in the active set**. Period. This may put someone that gets nominated not by the 1kv in disadvantage, but it is a tradeoff for now.

quick solution implemented [here](https://github.com/w3f/1k-validators-be/pull/2570)

**Comment by wpank** [comment]
closing this, as is implemented in https://github.com/w3f/1k-validators-be/pull/2570
