### ISSUE TITLE
Voting incentives cause automatic NAY votes

### ISSUE THREAD

**Issue by ggwpez** [w3f/1k-validators-be#2536]
The Democracy incentive as per [Wiki](https://wiki.polkadot.network/docs/thousand-validators#democracy) 

>Candidates will receive 10 * 1KV points for each referendum they have voted on (Aye/Nay) to a limit of 100 points. Scores are based on votes for referendum 49 and beyond.

This causes multiple validators to setup an auto-vote bot that NAYs everything. Its an issue since this gives off a wrong impression of overwhelmingly negative sentiment for new proposals.

**Comment by bkchr** [comment]
@wpank what is the status of this?

**Comment by eskimor** [comment]
Only get points if your vote aligns with the eventual result? + Get less points the later you vote?

**Comment by bkchr** [comment]
> Only get points if your vote aligns with the eventual result?

Then you incentivize the people to vote with what the "majority" says. Also sounds incorrect to me.

**Comment by wpank** [comment]
Copying an excerpt from the docs:

> As part of building one's own brand and reputation, participating in governance is one way to become more known amongst the community, and as such there's an `openGovDelegation` and `openGov` weight. Having a higher number of governance delegations, and consistently voting on governance proposals will increase the score for these factors. Having someone delegate their governance vote means that they trust their delegate with their decision making process in governance, and one can help build their own brand and reputation by providing value to the ecosystem via their governance participation. For `openGov` scoring, this is higher for the amount of votes a validator has (also adjusted for when they started participating in voting), although it does not matter with how much they vote, which vote direction they make (`aye`, `nay`, or `abstain`), nor whether they vote themselves or their vote lands on chain because they delegate to someone else. As such if someone does not care as much to be involved in governance, they can still earn a higher score by delegating their vote to someone else, as there are many people in the community that consistently and thoughtfully vote in governance. The balance of these factors is to promote validators to be engaged in governance as value-providing delegates that also attract delegations from others (as ideally they are voting and participating in a way that their delegators approve of), or to encourage validators to back other validators or ecosystem participants that are engaged in governance. 

----

Although last week it was announced to validators that socring related to open gov and delegating is being removed, so closing this.
