### ISSUE TITLE
Dry run and Test deprecation cleaning

### ISSUE THREAD

**Issue by ironoa** [w3f/1k-validators-be#2571]
related to https://github.com/w3f/1k-validators-be/pull/2570

<img width="914" alt="image" src="https://github.com/w3f/1k-validators-be/assets/25957738/7c27103d-8d8e-47c9-a6df-f7eeb319961c">

**Comment by ironoa** [comment]
dryrun is still present if you [search for it](https://github.com/search?q=repo%3Aw3f%2F1k-validators-be%20dryRun&type=code). [Here](https://github.com/w3f/1k-validators-be/pull/2586/files), The global dryrun is sometimes removed sometimes not, is that expected ?

**Comment by ironoa** [comment]
https://github.com/w3f/1k-validators-be-PRIVATE/issues/47

**Comment by wpank** [comment]
can be closed with  #2730
