### ISSUE TITLE
Bug Thread 'main' panicked at 'raise_fd_limit: error calling setrlimit: Operation not permitted (os error 1)', I have been faced this issue when Validator have been active that cause it to fail

### ISSUE THREAD

**Issue by nokogirisrv** [w3f/1k-validators-be#2704]
I am 1kv validator for a long time. I have 2 fail issues in my history, but they happened not by my fault. It was caused by the bug that has been reported to the dev team. Is it possible to remove those failures from my history because I am very focused on providing validation services of the best possible quality. I am also one of the best validators by performance.
Link to report for the bug:
https://github.com/paritytech/polkadot-sdk/issues/2744

My validator address:
HvUaoMXAcKNe17zaXGAJvH9ugQk1PRAuzGMKvtck6DV7pvr

My validator name:
Nokogrisrsrv

`Logs:
====================

Version: 1.4.0-00395a23d12

0: sp_panic_handler::set::{{closure}}
1: <alloc::boxed::Box<F,A> as core::ops::function::Fn>::call
at rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/boxed.rs:2021:9
std::panicking::rust_panic_with_hook
at rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:711:13
2: std::panicking::begin_panic_handler::{{closure}}
at rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:599:13
3: std::sys_common::backtrace::__rust_end_short_backtrace
at rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:170:18
4: rust_begin_unwind
at rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
5: core::panicking::panic_fmt
at rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
6: polkadot_cli::command::run
7: polkadot::main
8: std::sys_common::backtrace::__rust_begin_short_backtrace
9: main
10:
11: __libc_start_main
12: _start

Thread 'main' panicked at 'raise_fd_limit: error calling setrlimit: Operation not permitted (os error 1)', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/fdlimit-0.2.1/src/lib.rs:105

This is a bug. Please report it at:

    https://github.com/paritytech/polkadot-sdk/issues/new`

**Comment by Noc2** [comment]
I'm closing the issue. You should have received an email from us. Let me know if you have any other questions.
