### ISSUE TITLE
Validators frequently being marked invalid temporarily

### ISSUE THREAD

**Issue by validorange** [w3f/1k-validators-be#2805]
The SubVT bot on Telegram monitors the 1KV backend and reports changes to validator status.  Recently I am seeing a pattern where my validator is being marked invalid, then recovers after a short time, and this cycle repeats, despite no changes to my validator.  Several other folks have reported similar issues in the validator lounges.

I am assuming this issue is with the 1KV backend, and SubVT is just reporting it, so I am reporting this as an issue here rather than on SubVT.

Example:

SubVT Polkadot Bot, [3/21/2024 4:52 PM]
ValidOrange
❌ has become an invalid 1KV validator:
- validorange-dot1 does not have a validate intention.
- validorange-dot1 does not have an identity set.
- validorange-dot1 {}

SubVT Polkadot Bot, [3/21/2024 5:33 PM]
ValidOrange
✅ is now a valid 1KV validator.

SubVT Polkadot Bot, [3/21/2024 5:48 PM]
ValidOrange
❌ has become an invalid 1KV validator:
- validorange-dot1 does not have a validate intention.
- validorange-dot1 does not have an identity set.
- validorange-dot1 {}

SubVT Polkadot Bot, [3/21/2024 6:08 PM]
ValidOrange
✅ is now a valid 1KV validator.

SubVT Polkadot Bot, [3/21/2024 6:24 PM]
ValidOrange
❌ has become an invalid 1KV validator:
- validorange-dot1 does not have a validate intention.
- validorange-dot1 does not have an identity set.
- validorange-dot1 {}

SubVT Polkadot Bot, [3/21/2024 6:39 PM]
ValidOrange
✅ is now a valid 1KV validator.

SubVT Polkadot Bot, [3/21/2024 8:10 PM]
ValidOrange
❌ has become an invalid 1KV validator:
- validorange-dot1 does not have a validate intention.
- validorange-dot1 does not have an identity set.
- validorange-dot1 {}

SubVT Polkadot Bot, [3/21/2024 8:47 PM]
ValidOrange
✅ is now a valid 1KV validator.

SubVT Polkadot Bot, [3/21/2024 11:09 PM]
ValidOrange
❌ has become an invalid 1KV validator:
- validorange-dot1 does not have a validate intention.
- validorange-dot1 does not have an identity set.
- validorange-dot1 {}

SubVT Polkadot Bot, [3/22/2024 12:15 AM]
ValidOrange
✅ is now a valid 1KV validator.

**Comment by ironoa** [comment]
Thanks for reporting.

There was a bug with the handling of the Api connection in version [3.1.9](https://github.com/w3f/1k-validators-be/releases/tag/v3.1.9), the [latest release](https://github.com/w3f/1k-validators-be/releases/tag/v3.1.11) from @wpank should have fixed it 

Leaving the issue open for now...

**Comment by ironoa** [comment]
situation seems stable, feel free to reopen in case...
