### ISSUE TITLE
Many validators have invalid status due to out-of-date polkadot version in BE

### ISSUE THREAD

**Issue by dcolley** [w3f/1k-validators-be#2837]
https://dev.metaspan.io/kusama/candidate/HyLisujX7Cr6D7xzb6qadFdedLt8hmArB6ZVGJ6xsCUHqmx
https://dev.metaspan.io/kusama/candidate/JKhBBSWkr8BJKh5eFBtRux4hsDq4sAxvvmMU426qUA9aqEQ

https://telemetry.w3f.community/#list/0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe
<img width="1015" alt="image" src="https://github.com/w3f/1k-validators-be/assets/1845970/07e32dda-429f-4142-a94a-080855b4d0ee">

https://kusama.w3f.community/candidate/HyLisujX7Cr6D7xzb6qadFdedLt8hmArB6ZVGJ6xsCUHqmx
```json
        {
            "valid": false,
            "type": "CLIENT_UPGRADE",
            "details": "METASPAN (also try POOL #50) is not on the latest client version",
            "updated": 1712487164659,
            "_id": "66127afcaae0fdb24e41c9c8"
        },
// The timestamp 1712487164659 corresponds to the date and time 2024-04-07T10:52:44.659000 UTC.
```

**Comment by ironoa** [comment]
Hey Derek,

I'm not sure about the title you gave to this issue.

Anyway, your telemetry name and [candidate name](https://github.com/w3f/1k-validators-be/blob/master/candidates/kusama.json#L2996) don't match, I suggest that you start by syncing them. 
(capital case)
![image](https://github.com/w3f/1k-validators-be/assets/25957738/146fad3c-b366-4c0b-ad48-603d0e09c354)
<img width="571" alt="image" src="https://github.com/w3f/1k-validators-be/assets/25957738/ed1a6c4f-69cc-4ce6-b9b6-23710d360a53">

**Comment by dcolley** [comment]
Yes, that was the problem, thanks!
