### ISSUE TITLE
Invalid 1kv status for dakkk/2 on Kusama

### ISSUE THREAD

**Issue by dakk** [w3f/1k-validators-be#2881]
My node is "Invalid" for wrong software version and offline, but the node is online at the latest version on telemetry; address is G2JyVQGxihdKXDBCC6BYNvsrY9NT4CsxfJ9dF1kjsyX2PJv

https://kusama.w3f.community/candidate/G2JyVQGxihdKXDBCC6BYNvsrY9NT4CsxfJ9dF1kjsyX2PJv

**Comment by ddozen** [comment]
According to telemetry you named your node dakk2 while in 1kv name is dakkk2.

**Comment by ironoa** [comment]
closing since invalidity was caused by the telemetry name mismatch

**Comment by dakk** [comment]
Got it, sorry for the mistake
