### ISSUE TITLE
I don't receive a reply about my 1KV application

### ISSUE THREAD

**Issue by tradewisevalidator** [w3f/1k-validators-be#2921]
Good afternoon, I submitted my application to join the 1KV program over 3 weeks ago, Kuba confirmed my matrix, but for some reason (which I am not informed of, although I keep asking this question) they are not responding. Please add me to the program or clearly explain the reason for the rejection. 
Code in case of approval:)
},
    {
      "slotId": 913,
      { "name": "Tradewise",
      "stash": "CuTiFjeDeHRzLeYomDLBWjRd8v7MU7dm4428kK6n5LwuXqc",
      { "riotHandle": "@tradewise:matrix.org",
      "kyc": true
},
    {
      "slotId": 914,
      { "name": "Tradewise-01",
      "stash": "HnSKG3Tx3mfnsReg9PpJ59vwu26LRbqoYgZHij4fNvRYpFA",
      { "riotHandle": "@tradewise:matrix.org",
      "kyc": true
}
  ]
}

**Comment by kubaw3f** [comment]
Application of the candidate rejected, the reasons communicated to the candidate directly
