### ISSUE TITLE
Improve nominations to happen every set amount of eras

### ISSUE THREAD

**Issue by lsaether** [w3f/1k-validators-be#455]
... instead of 24 hour intervals.

**Comment by wpank** [comment]
It would make sense to send the nomination the after the 4th or 5th session in an era so that the next election takes into account those nominations. For Kusama, this can be every 6 eras.

**Comment by iisaint** [comment]
May I ask a question about the Phragmén algorithm?
Is every election independent or not? If yes, there is no need to adjust the nominations in every era. If no, what is the best strategy to achieve stable and predictable income?
Thank you in advance.

**Comment by wpank** [comment]
@iisaint yes every election is independent. But many Validators will change their status in between eras (ie they may go offline, may change their commission, etc). Which means some may not be valid anymore. So every era, nominations are only done for those that are valid, as to not waste nominations on invalid nodes.

**Comment by lsaether** [comment]
The goal of this issue is to make the current nominating schedule more controlled and reliable. Along with #142 this will make it so that nominations should be more regular to all validators since we can begin to target validators that are not included in the elected set. For example, if we routinely nominate a set of 16 validators but only 5 are elected during one nomination period, we would like to make it so that we can target the nomination to the other 11 for the next nomination period.
