### ISSUE TITLE
Candidate Endpoint Improvements

### ISSUE THREAD

**Issue by wpank** [w3f/1k-validators-be#457]
- [ ] Remove SentryId, SentryOnlineSince, SentryOfflineSince
- [ ] Include an array of `InvalidityReasons`

For Polkadot:
- [ ] Include Kusama 1kv Address

**Comment by lsaether** [comment]
@wpank Why remove faults? It's how we keep track the number of times a validator was deducted points. Part of the rules to stay in the program is to have < 3 faults.
