### ISSUE TITLE
Tech stack Validator node

### ISSUE THREAD

**Issue by roy-m-organ** [w3f/1k-validators-be#583]

**Comment by lsaether** [comment]
@roy-m-organ Can you give me more context on this issue?

**Comment by roy-m-organ** [comment]
I don't know, probably works fine  I have already loaded another now so the build as been rooted. Probably because I didn't have julia/rust I do now.

**Comment by lsaether** [comment]
Ok! closing this then...

**Comment by roy-m-organ** [comment]
Ok thank you
